// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func FindSupplier() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><div class=\"row\"><div class=\"col-auto\"><h1>Step 1: Find a supplier!</h1></div></div><div class=\"row\"><div class=\"col-auto\"><ul><li><em>Finding a Supplier or Broker: </em>Average (8+) Broker check (1D6 days, EDU or SOC)</li><li><em>Finding a Black Market Supplier or Broker of Illegal Goods: </em>Average (8+) Streetwise check (1D6 days, EDU or SOC)</li><li><em>Finding an Online Supplier or Broker (TL8+ worlds only): </em>Average (8+) Admin check (1D6 hours, EDU)</li></ul></div></div><div class=\"row mt-4\"><div class=\"col-auto\"><p>The size of the Starport provides a bonus to finding a supplier.</p><table class=\"table table-dark border border-1 border-secondary\"><tr><td>Class A</td><td>DM +6</td></tr><tr><td>Class B</td><td>DM +4</td></tr><tr><td>Class C</td><td>DM +2</td></tr></table></div></div><a href=\"#\" class=\"btn btn-primary mt-4\" hx-get=\"/spec-trade-purchase?step=2\" hx-target=\"#content\" hx-swap=\"innerHTML\">Determine Goods Available</a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
